name: 'Conventional PRs'
description: "Enforce conventional commit style in your project's pull requests"
author: 'Cristopher Namchee'
inputs:
  access_token:
    description: 'GitHub Access Token'
    required: true
  check_draft:
    description: 'Determine whether Conventional PR should check draft PRs'
    required: false
    default: false
  label:
    description: 'Nonconventional PRs label'
    required: false
    default: 'Nonconventional'
  close:
    description: 'Determine whether Conventional PR should close nonconventional PRs'
    required: false
    default: true
  template:
    description: 'Comment header on invalid PRs'
    required: false
    default: |-
      Thank you for your contribution attempt in this repository!
      
      Unfortunately, this pull request doesn't meet our standards by reason we stated below. Please create another pull request that meets our standards in the future.
  strict:
    description: 'Determine whether the current restriction should also apply to repository administrators'
    required: false
    default: true
  allowed_types:
    description: 'List of allowed conventional commit types'
    required: false
    default: ''
  allowed_scopes:
    description: 'List of allowed conventional commit scopes'
    required: false
    default: ''
  maximum_file_change:
    description: 'Limits how many files should be changes per pull request'
    required: false
    default: 0
  link_issue:
    description: 'Determine whether a conventional PR should always refer to an issue'
    required: false
    default: true
  ignore_bot:
    description: 'Determine whether PR checking should be skipped on PRs that is created by bots'
    required: false
    default: true
runs:
  using: docker
  image: 'Dockerfile'
branding:
  icon: 'compass'
  color: 'gray-dark'
