name: Conventional PR
description: "Validates and enforces clean pull request style in your GitHub projects without hassle"
author: "Cristopher Namchee"
inputs:
  access_token:
    description: "GitHub account access token"
    required: true
  close:
    description: "Determine whether checks should close invalid pull requests"
    required: false
    default: true
  label:
    description: "Invalid pull requests label"
    required: false
    default: "cpr:invalid"
  template:
    description: "Comment template on invalid pull requests"
    required: false
    default: ""
  draft:
    description: "Determine whether checks should be skipped pull request is a draft"
    required: false
    default: true
  strict:
    description: "Determine whether checks should also apply to repository administrators"
    required: false
    default: true
  bot:
    description: "Determine whether checks should be skipped if the author is a bot"
    required: false
    default: true
  title_pattern:
    description: "Valid pull request title regex pattern in Perl syntax"
    required: false
    default: '([\w\-]+)(\([\w\-]+\))?!?: [\w\s:\-]+'
  commit_pattern:
    description: "Valid pull request commit message regex pattern in Perl syntax"
    required: false
    default: ""
  branch_pattern:
    description: "Valid pull request branch name regex pattern in Perl syntax"
    required: false
    default: ""
  issue:
    description: "Determine whether a valid pull request should always refer to an issue"
    required: false
    default: true
  body:
    description: "Determine whether a valid pull request should have a non-empty body"
    required: false
    default: true
  maximum_file_changes:
    description: "Limits how many files should be changes per pull request"
    required: false
    default: 0
  verified_commits:
    description: "Require all commits to be verified or signed with GPG keys"
    required: false
    default: false
  ignored_users:
    description: "GitHub usernames to be whitelisted from pull request validation"
    required: false
    default: ""
  report:
    description: "Determines whether pull request report should be written as a pull request comment"
    required: false
    default: true
runs:
  using: docker
  image: "Dockerfile"
branding:
  icon: "compass"
  color: "gray-dark"
