name: 'Ethos'
description: "Enforce conventional commit style in your project's pull requests"
author: 'Cristopher Namchee'
inputs:
  access_token:
    description: 'GitHub account access token'
    required: false
    default: ""
  check_draft:
    description: 'Determine whether checks should be skipped pull request is a draft'
    required: false
    default: true
  close:
    description: 'Determine whether checks should close invalid PRs'
    required: false
    default: true
  label:
    description: 'Invalid PRs label'
    required: false
    default: 'ethos:invalid'
  template:
    description: 'Comment template on invalid PRs'
    required: false
    default: ""
  strict:
    description: 'Determine whether checks should also apply to repository administrators'
    required: false
    default: true
  maximum_file_changes:
    description: 'Limits how many files should be changes per pull request'
    required: false
    default: 0
  link_issue:
    description: 'Determine whether a valid PR should always refer to an issue'
    required: false
    default: true
  ignore_bot:
    description: 'Determine whether checks should be skipped if the author is a bot'
    required: false
    default: true
  check_commits:
    description: 'Determine whether checks should also be applied to all commits in the pull request'
    required: false
    default: false
  pattern:
    description: 'Valid pull request title and commit message pattern in Perl syntax'
    required: false
    default: "([\w\-]+)(\([\w\-]+\))?!?: [\w\s:\-]+"
runs:
  using: docker
  image: 'Dockerfile'
branding:
  icon: 'compass'
  color: 'gray-dark'
