package constants

// Report template
var (
	ReportHeader = `## **Pull Request Validation Report**

*This comment is automatically generated by [Conventional PR](https://github.com/Namchee/conventional-pr)*`
	WhitelistTemplate = `### **Whitelist Report**

%s

%s`
	ValidatorTemplate = `### **Validation Report**

%s

%s`
	ResultTemplate = `**Result**

%s`
	ReasonTemplate = `**Reason**

%s`
	WhitelistPass  = "Pull request matches with one (or more) enabled whitelist criteria. Pull request validation is skipped."
	WhitelistFail  = "Pull request does not satisfy any enabled whitelist criteria. Pull request will be validated."
	ValidationPass = "Pull request satisfies all enabled pull request rules."
	ValidationFail = "Pull request is invalid."

	LogHeader = `
 ____                            _   _                   _ ____  ____  
/ ___| ___  _ ____   _____ _ __ | |_(_) ___  _ __   __ _| |  _ \|  _ \ 
| |   / _ \| '_ \ \ / / _ \ '_ \| __| |/ _ \| '_ \ / _ || | |_) | |_) |
| |__| (_) | | | \ V /  __/ | | | |_| | (_) | | | | (_||| |  __/|  _ < 
\____ \___/|_| |_|\_/ \___|_| |_|\__|_|\___/|_| |_|\__,_|_|_|   |_| \_\`
)

// Emojis

const (
	// PassEmoji is the emoji to use when a whitelist or validator pass
	PassEmoji = "✅"
	// FailEmoji is the emoji to use when a whitelist or validator fails
	FailEmoji = "❌"
)
