package constants

// Report template
var (
	ReportHeader = `### **Pull Request Validation Report**

*This comment is automatically generated by [ethos](https://github.com/Namchee/conventional-pr)*`
	WhitelistTemplate = `#### **Whitelist Report**

%s

%s`
	ValidatorTemplate = `#### **Validation Report**

%s

%s`
	ResultTemplate = `**Result**

%s`
	ReasonTemplate = `**Reason**

%s`
	WhitelistPass  = "Pull request matches with one (or more) enabled whitelist criteria. Pull request validation is skipped."
	WhitelistFail  = "Pull request does not satisfy any enabled whitelist criteria. Pull request will be validated."
	ValidationPass = "Pull request satisfies all enabled pull request rules."
	ValidationFail = "Pull request is invalid."
)

// Emojis

const (
	PassEmoji = "✅"
	FailEmoji = "❌"
)
