name: Check PR semantics

on: pull_request

jobs:
  conventional-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR semantics
        uses: Namchee/conventional-pr@master
        with:
          access_token: ${{ secrets.ACCESS_TOKEN }}