name: Check PR semantics

on: pull_request

jobs:
  hqprs:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR semantics
        uses: Namchee/conventional-pr@v0.1.0
        with:
          access_token: ${{ secrets.ACCESS_TOKEN }}