name: Check PR semantics

on:
  pull_request_target:

jobs:
  cpr:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR semantics
        uses: Namchee/conventional-pr@master
        with:
          access_token: ${{ secrets.ACCESS_TOKEN }}
          edit: true
