name: Check PR semantics

on:
  pull_request_target:

jobs:
  cpr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check PR semantics
        uses: ./
        with:
          access_token: ${{ secrets.ACCESS_TOKEN }}
  
