name: Do self test

on:
  pull_request_target:

jobs:
  cpr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test validation to self
        uses: ./
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
          edit: true
          verbose: true

